vich_uploader:
    db_driver: orm

    mappings:
        imagen:
            uri_prefix: /archivos/imagenes
            upload_destination: '%kernel.project_dir%/public/archivos/imagenes'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        video:
            uri_prefix: /archivos/videos
            upload_destination: '%kernel.project_dir%/public/archivos/videos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        audio:
            uri_prefix: /archivos/audios
            upload_destination: '%kernel.project_dir%/public/archivos/audios'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        modelo3d:
            uri_prefix: /archivos/modelo3d
            upload_destination: '%kernel.project_dir%/public/archivos/modelos3d'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        fichero:
            uri_prefix: /archivos/ficheros
            upload_destination: '%kernel.project_dir%/public/archivos/ficheros'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
